# Generated by Django 3.0.8 on 2020-09-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_app', '0002_feeding_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='toys',
            field=models.ManyToManyField(to='dog_app.Toy'),
        ),
    ]
